#!/usr/bin/env python3
"""Import qwen-web-arwaky swarm agent outputs as GitHub Issues.

Reads every ``*/output.md`` in a swarm run directory, extracts the structured
``#### Issue`` blocks generated by the role templates, and creates matching
GitHub Issues in a target repository. Interactive mode walks the user through
folder selection, project selection, preview, and confirmation.

No external dependencies beyond the standard library; GitHub is accessed
directly over the REST API using a ``gh`` auth token or ``GITHUB_TOKEN``.

Usage:
    # Fully interactive (prompts for folder, project, preview):
    python3 scripts/swarm_to_issues.py

    # Non-interactive:
    python3 scripts/swarm_to_issues.py --folder /path/to/swarm --repo owner/repo --yes
    python3 scripts/swarm_to_issues.py --folder /path/to/swarm --repo owner/repo --dry-run

Exit codes:
    0 success (or dry-run completed)
    1 fatal error (no issues found, auth failure, user abort, ...)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Role registry — mirrors the templates in modules/templates/*.md.
# ---------------------------------------------------------------------------

ROLE_PREFIX = {
    "backend-engineer": "BE",
    "business-analyst": "BA",
    "devops-engineer": "DO",
    "frontend-engineer": "FE",
    "product-engineer": "PE",
    "qa-engineer": "QA",
    "security-engineer": "SE",
    "software-architect": "ARCH",
    "system-analyst": "SA",
    "ui-ux-designer": "UX",
}

ROLE_LABEL = {role: f"swarm-{role}" for role in ROLE_PREFIX}

ROLE_SCOPE_NOTE = {
    "backend-engineer": "Backend Engineering review",
    "business-analyst": "Business Analyst review",
    "devops-engineer": "DevOps review",
    "frontend-engineer": "Frontend Engineering review",
    "product-engineer": "Product Engineering review",
    "qa-engineer": "QA review",
    "security-engineer": "Security review",
    "software-architect": "Software Architect review",
    "system-analyst": "System Analyst review",
    "ui-ux-designer": "UI/UX Design review",
}

SEVERITY_LABELS = ("critical", "warning", "info")
LABEL_COLORS = {
    "swarm-backend-engineer": "5319E7",
    "swarm-business-analyst": "5319E7",
    "swarm-devops-engineer": "5319E7",
    "swarm-frontend-engineer": "5319E7",
    "swarm-product-engineer": "5319E7",
    "swarm-qa-engineer": "5319E7",
    "swarm-security-engineer": "B60205",
    "swarm-software-architect": "BFD4F2",
    "swarm-system-analyst": "5319E7",
    "swarm-ui-ux-designer": "BFD4F2",
    "severity-critical": "B60205",
    "severity-warning": "FBCA04",
    "severity-info": "0E8A16",
}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class SwarmIssue:
    """A single parsed issue ready for import."""

    issue_id: str
    role: str
    title: str
    body: str
    labels: list[str] = field(default_factory=list)

    @property
    def role_label(self) -> str:
        return ROLE_LABEL.get(self.role, "swarm-unknown")

    @property
    def dedup_key(self) -> str:
        """Stable identifier used for idempotent re-runs."""
        return f"{self.role}:{self.issue_id}"


@dataclass
class ImportResult:
    created: list[SwarmIssue] = field(default_factory=list)
    skipped_existing: list[SwarmIssue] = field(default_factory=list)
    skipped_duplicate_in_batch: list[SwarmIssue] = field(default_factory=list)
    errors: list[tuple[SwarmIssue, str]] = field(default_factory=list)

    @property
    def total(self) -> int:
        return len(self.created) + len(self.skipped_existing) + len(self.errors)

    @property
    def ok(self) -> bool:
        return not self.errors


# ---------------------------------------------------------------------------
# Swarm folder discovery
# ---------------------------------------------------------------------------


def discover_swarm_runs(base: Path) -> list[Path]:
    """Find swarm run directories (containing a manifest.json) under ``base``.

    ``base`` may point directly at a run directory or at a directory that
    contains one or more runs.
    """
    if not base.is_dir():
        return []
    runs: list[Path] = []
    if (base / "manifest.json").is_file():
        runs.append(base)
    for sub in sorted(base.iterdir()):
        if sub.is_dir() and (sub / "manifest.json").is_file():
            runs.append(sub)
    # Deeper nesting (swarm_root/swarm_*/<run>):
    if not runs:
        for sub in sorted(base.iterdir()):
            if sub.is_dir():
                for deeper in sorted(sub.iterdir()):
                    if deeper.is_dir() and (deeper / "manifest.json").is_file():
                        runs.append(deeper)
    # De-dup, keep order
    seen: set[Path] = set()
    out: list[Path] = []
    for r in runs:
        rp = r.resolve()
        if rp not in seen:
            seen.add(rp)
            out.append(r)
    return out


def read_manifest(run: Path) -> dict:
    try:
        return json.loads((run / "manifest.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


# ---------------------------------------------------------------------------
# Issue parser
# ---------------------------------------------------------------------------

ROLE_DETECT = re.compile(r"####\s+Issue\s+([A-Z]+-\d+-\d+)\s*$")


def _strip_md_escapes(s: str) -> str:
    """Strip markdown escape backslashes, iterating until stable."""
    prev = None
    while prev != s:
        prev = s
        out = []
        i = 0
        while i < len(s):
            c = s[i]
            if c == "\\" and i + 1 < len(s) and s[i + 1] in "[]`_*\\":
                out.append(s[i + 1])
                i += 2
            else:
                out.append(c)
                i += 1
        s = "".join(out)
    return s


def build_issue_body(
    role: str,
    iid: str,
    description: str,
    plan_title: str,
    swarm_id: str,
    open_questions: str = "",
) -> str:
    parts = [
        f"## {ROLE_SCOPE_NOTE.get(role, 'Swarm review')}",
        "",
        f"**Agent**: `{role}`",
        "",
        f"**Swarm Run**: `{swarm_id}`",
    ]
    if plan_title:
        parts += ["", f"**Source Plan**: {plan_title}"]
    parts += ["", f"**Issue ID**: `{iid}`", "", "---", "", description]
    if open_questions.strip().lower() not in ("", "none", "-"):
        parts += ["", "## Open Questions", open_questions.strip()]
    parts += ["", "---", ""]
    parts.append(f"*Auto-created from qwen-web-arwaky swarm run `{swarm_id}` (`{role}`); imported `{iid}`.*")
    return "\n".join(parts)


def parse_agent_output(role: str, path: Path, swarm_id: str) -> list[SwarmIssue]:
    """Extract every ``#### Issue`` block from one agent's output.md."""
    text = path.read_text(encoding="utf-8", errors="replace")

    plan_title = ""
    for ln in text.splitlines():
        if ln.startswith("# "):
            plan_title = ln[2:].strip()
            break

    issues: list[SwarmIssue] = []
    cur: dict | None = None
    collecting_desc: str | None = None
    in_code = False
    code_lines: list[str] = []

    def flush() -> None:
        nonlocal cur, collecting_desc, in_code
        if cur is not None:
            desc = "\n".join(cur["desc"]).strip()
            open_q = "\n".join(cur["open_q"]).strip()
            if cur.get("title"):
                body = build_issue_body(cur["role"], cur["id"], desc, plan_title, swarm_id, open_q)
                # Labels: explicit list from the template first, else infer
                # role + severity from the title.
                if cur.get("explicit_labels"):
                    labels: list[str] = [cur["role_label"]] + cur["explicit_labels"]
                else:
                    labels = [cur["role_label"]]
                    for sev in SEVERITY_LABELS:
                        if f"[{sev.upper()}]" in cur["title"]:
                            labels.append(f"severity-{sev}")
                seen_lbls: set[str] = set()
                labels = [lbl for lbl in labels if not (lbl in seen_lbls or seen_lbls.add(lbl))]
                issues.append(
                    SwarmIssue(
                        issue_id=cur["id"],
                        role=cur["role"],
                        title=cur["title"],
                        body=body,
                        labels=labels,
                    )
                )
        cur = None
        collecting_desc = None
        in_code = False

    for ln in text.splitlines():
        m = ROLE_DETECT.match(ln)
        if m:
            flush()
            prefix = m.group(1).split("-")[0]
            # Map the issue-id prefix back to a registered role when possible
            role_by_prefix = next(
                (r for r, p in ROLE_PREFIX.items() if p == prefix),
                role,
            )
            cur = {
                "id": m.group(1),
                "role": role_by_prefix,
                "role_label": ROLE_LABEL.get(role_by_prefix, "swarm-unknown"),
                "title": "",
                "desc": [],
                "open_q": [],
                "explicit_labels": [],
            }
            collecting_desc = None
            in_code = False
            code_lines = []
            continue

        if cur is None:
            continue

        if in_code:
            code_lines.append(ln)
            if ln.strip().startswith("```"):
                in_code = False
                cur["desc"].extend(code_lines)
                code_lines = []
            continue

        stripped = ln.strip()
        if stripped.startswith("```"):
            # If the current field is description-ish, the fenced block belongs to it
            in_code = True
            code_lines = [ln]
            continue

        tm = re.match(r"^-\s*\*\*Title\*\*:\s*(.+)$", ln)
        if tm:
            cur["title"] = _strip_md_escapes(tm.group(1).strip())
            collecting_desc = None
            continue

        lml = re.match(r"^-\s*\*\*Label\*\*:\s*(.*)$", ln)
        if lml:
            raw = lml.group(1).strip()
            # Accept a `{a|b|c}` candidate list (pipe-separated) or a plain
            # comma-separated list; both are normalised to one label each.
            if raw.startswith("{") and raw.endswith("}"):
                raw = raw[1:-1]
            if raw:
                parts = re.split(r"[,|]", raw)
                seen: set[str] = set()
                cur["explicit_labels"] = [
                    p.strip() for p in parts if p.strip() and not (p.strip() in seen or seen.add(p.strip()))
                ]
            collecting_desc = None
            continue

        om = re.match(r"^-\s*\*\*Open Questions\*\*:\s*(.*)$", ln)
        if om:
            rest = om.group(1).strip()
            if rest:
                cur["open_q"].append(rest)
            collecting_desc = "open_q"
            continue

        lm = re.match(r"^-\s*\*\*Location Path\*\*:?\s*(.*)$", ln)
        if lm:
            cur["desc"].append("## Location Path")
            rest = lm.group(1).strip()
            if rest:
                cur["desc"].append(rest)
            collecting_desc = "desc"
            continue

        dm = re.match(r"^-\s*\*\*(Description)\*\*:\s*(.*)$", ln)
        if dm:
            cur["desc"].append("## Description")
            if dm.group(2).strip():
                cur["desc"].append(dm.group(2).strip())
            collecting_desc = "desc"
            continue

        am = re.match(r"^-\s*\*\*(Acceptance Criteria)\*\*:\s*(.*)$", ln)
        if am:
            cur["desc"].append("## Acceptance Criteria")
            if am.group(2).strip():
                cur["desc"].append(am.group(2).strip())
            collecting_desc = None
            continue

        rm = re.match(r"^-\s*\*\*(Recommendation)\*\*:\s*(.*)$", ln)
        if rm:
            cur["desc"].append("## Recommendation")
            if rm.group(2).strip():
                cur["desc"].append(rm.group(2).strip())
            collecting_desc = None
            continue

        gm = re.match(r"^-\s*\*\*(Git Diff)\*\*:\s*$", ln)
        if gm:
            cur["desc"].append("## Suggested Diff")
            collecting_desc = None
            continue

        # Plain continuation lines while inside an active field block
        if collecting_desc and stripped and not stripped.startswith("- **"):
            if collecting_desc == "open_q":
                if stripped.lower() not in ("none", "-", "n/a"):
                    cur["open_q"].append(ln.rstrip())
            else:
                cur["desc"].append(ln.rstrip())
            continue

        # Generic sub-bullets (e.g. "**Severity**: ...") — keep them
        if stripped.startswith("- **") and not re.match(
            r"^-\s*\*\*(Title|Label|Location Path|Description|Acceptance "
            r"Criteria|Recommendation|Git Diff|Open Questions)\*\*",
            stripped,
        ):
            cur["desc"].append(stripped)

    flush()

    # If no structured issues found, fall back to whole-document summary
    if not issues and text.strip():
        issues.append(
            SwarmIssue(
                issue_id=f"DOC-{swarm_id[-4:]}",
                role=role,
                title=f"[{role}] Swarm output (unstructured) — {plan_title[:40]}",
                body=(
                    f"## {ROLE_SCOPE_NOTE.get(role, 'Swarm review')}\n\n"
                    f"**Agent**: `{role}`\n\n**Swarm Run**: `{swarm_id}`\n\n"
                    "---\n\n" + text.strip() + "\n"
                ),
                labels=[ROLE_LABEL.get(role, "swarm-unknown")],
            )
        )
    return issues


def parse_swarm_run(run: Path) -> list[SwarmIssue]:
    """Parse every ``*/output.md`` in a swarm run directory."""
    manifest = read_manifest(run)
    swarm_id = manifest.get("swarm_id", run.name)
    out: list[SwarmIssue] = []
    for d in sorted(run.iterdir()):
        if not d.is_dir():
            continue
        role = d.name
        outmd = d / "output.md"
        if not outmd.is_file():
            continue
        out.extend(parse_agent_output(role, outmd, swarm_id))
    # De-dup by (role, issue_id) — keep first occurrence
    seen: set[tuple[str, str]] = set()
    deduped: list[SwarmIssue] = []
    for it in out:
        key = (it.role, it.issue_id)
        if key not in seen:
            seen.add(key)
            deduped.append(it)
    return deduped


# ---------------------------------------------------------------------------
# GitHub client (stdlib only; token from `gh auth token` or GITHUB_TOKEN)
# ---------------------------------------------------------------------------


class GitHubClient:
    def __init__(self, base_url: str = "https://api.github.com", repo: str = ""):
        self.base_url = base_url.rstrip("/")
        self._repo = repo
        self._token: str | None = None

    def authenticate(self) -> None:
        token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
        if not token:
            gh = shutil.which("gh")
            if gh:
                try:
                    token = subprocess.run(
                        [gh, "auth", "token"],
                        capture_output=True,
                        text=True,
                        check=False,
                    ).stdout.strip()
                except OSError:
                    token = ""
        if not token:
            raise SystemExit("No GitHub token found. Set GITHUB_TOKEN or log in with `gh auth login`.")
        self._token = token

    def _req(self, method: str, path: str, payload: dict | None = None):
        # URL-encode the path (and its query string) so spaces / backticks /
        # other control characters are handled by urllib.request safely.
        url = f"{self.base_url}{urllib.parse.quote(path, safe='/:?&=')}"
        headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
        }
        data = None
        if payload is not None:
            headers["Content-Type"] = "application/json"
            data = json.dumps(payload).encode()
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw = resp.read()
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as e:
            err_body = e.read().decode(errors="replace")
            raise RuntimeError(f"GitHub API {method} {path} -> HTTP {e.code}: {err_body[:500]}") from e

    def list_labels(self) -> set[str]:
        labels = set()
        page = 1
        while True:
            batch = self._req(
                "GET",
                f"/repos/{self._repo}/labels?per_page=100&page={page}",
            )
            labels.update(entry["name"].lower() for entry in batch)
            if len(batch) < 100:
                break
            page += 1
        return labels

    def ensure_label(self, name: str, existing: set[str]) -> None:
        if name.lower() in existing:
            return
        color = LABEL_COLORS.get(name, "BFD4F2")
        try:
            self._req(
                "POST",
                f"/repos/{self._repo}/labels",
                {"name": name, "color": color, "description": name},
            )
            existing.add(name.lower())
            print(f"  + label created: {name}")
        except RuntimeError as e:
            # May be a race (label created in parallel) — warn and continue.
            print(f"  ! label {name}: {e}")

    def find_open_issue_number(self, issue: SwarmIssue) -> int | None:
        """Return the number of an open issue that matches this issue, else None.

        Dedup key is the stable ``Issue ID`` marker embedded in the body
        (e.g. ``BE-1-001``), which is far more reliable than matching the
        full human-readable title. The query is built raw; ``_req`` handles
        URL-encoding.
        """
        marker = f"imported `{issue.issue_id}`"
        q = f"repo:{self._repo} is:issue is:open {marker}"
        try:
            res = self._req("GET", f"/search/issues?q={q}&per_page=5")
            for item in res.get("items", []):
                body = item.get("body") or ""
                if f"imported `{issue.issue_id}`" in body:
                    return int(item["number"])
        except RuntimeError:
            pass
        return None

    def create_issue(self, title: str, body: str, labels: list[str]) -> int:
        payload = {"title": title, "body": body, "labels": labels}
        res = self._req("POST", f"/repos/{self._repo}/issues", payload)
        return int(res["number"])


# ---------------------------------------------------------------------------
# Interactive helpers
# ---------------------------------------------------------------------------


def _prompt(text: str) -> str:
    try:
        return input(text).strip()
    except (EOFError, KeyboardInterrupt) as err:
        print("\nAborted.")
        raise SystemExit(1) from err


def _prompt_choice(prompt: str, choices: list[str], allow_input: bool = True) -> str:
    """Numbered selection with free-text fallback."""
    print(prompt)
    for i, c in enumerate(choices, 1):
        print(f"  {i:2d}) {c}")
    if allow_input:
        extra = "  m) manual entry"
        print(extra)
    while True:
        val = _prompt(f"Select 1-{len(choices)}" + (" or m" if allow_input else "") + ": ")
        if val.isdigit() and 1 <= int(val) <= len(choices):
            return choices[int(val) - 1]
        if allow_input and val.lower() == "m":
            return _prompt("Enter value: ")
        print("Invalid selection, try again.")


def detect_local_github_projects() -> list[tuple[str, str]]:
    """Heuristically detect `owner/repo` values from local git worktrees.

    Looks for .git config files whose origin URL matches a GitHub repo and
    collects the (owner, repo) pairs it has already seen.
    """
    projects: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    git_cfg_candidates = []
    home = Path.home()
    for root in (home / ".orca" / "workspaces", home / "workspaces", home):
        git_cfg_candidates.extend(root.glob("*/.git"))
        git_cfg_candidates.extend(root.glob("*/.git/config"))
    for p in git_cfg_candidates:
        cfg = p if p.name == "config" else p / "config"
        if not cfg.is_file():
            continue
        try:
            content = cfg.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        m = re.search(
            r"url\s*=\s*(?:https?://|git@)github\.com[:/]([\w.-]+)/([\w.-]+?)(?:\.git)?\s*$",
            content,
            re.MULTILINE,
        )
        if m:
            owner, repo = m.group(1), m.group(2)
            key = (owner, repo)
            if key not in seen:
                seen.add(key)
                projects.append(key)
    # Always include the known repo as a hint
    known = ("rakaarwaky", "qwen-web-arwaky")
    if known not in seen:
        projects.insert(0, known)
    return projects


def prompt_swarm_folder() -> Path:
    default_root = Path.home() / ".local" / "share" / "qwen-web-arwaky" / "swarm"
    found = discover_swarm_runs(default_root) if default_root.is_dir() else []
    print("Swarm run candidates under ~/.local/share/qwen-web-arwaky/swarm:")
    if not found:
        print("  (none found — you will be asked to type a path)")
    for i, p in enumerate(found, 1):
        man = read_manifest(p)
        status = man.get("status", "?")
        completed = man.get("completed", 0)
        total = man.get("agent_count", 0)
        print(f"  {i:2d}) {p}  [{status} {completed}/{total} agents]")
    choices = [str(p) for p in found]
    val = _prompt_choice("Pick a swarm run:", choices, allow_input=True)
    if val == "":
        val = _prompt("Type the path to a swarm run directory: ")
    p = Path(val)
    if not p.is_dir() or not (p / "manifest.json").is_file():
        raise SystemExit(f"Not a swarm run directory (missing manifest.json): {p}")
    return p.resolve()


def prompt_repo(detected: list[tuple[str, str]]) -> str:
    choices = [f"{o}/{r}" for o, r in detected]
    val = _prompt_choice("Target GitHub project (owner/repo):", choices, allow_input=True)
    if not re.match(r"^[\w.-]+/[\w.-]+$", val):
        raise SystemExit(f"Invalid owner/repo value: {val}")
    return val


# ---------------------------------------------------------------------------
# Preview + confirmation
# ---------------------------------------------------------------------------


def print_preview(issues: list[SwarmIssue]) -> None:
    print(f"\nParsed {len(issues)} issue(s):\n")
    for it in issues:
        print(f"  [{it.role}] {it.issue_id:12s}  {it.title[:64]}")
        print(f"                  labels: {', '.join(it.labels)}")
    print()


def confirm(message: str) -> bool:
    try:
        ans = input(f"{message} [y/N]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        return False
    return ans in ("y", "yes", "1", "true")


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--folder", help="Swarm run directory (default: prompt)")
    ap.add_argument("--repo", help="GitHub owner/repo (default: prompt)")
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse and preview only; do not call the GitHub API",
    )
    ap.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Skip interactive confirmation; create all issues immediately",
    )
    ap.add_argument(
        "--no-dedup",
        action="store_true",
        help="Disable dedup against open issues with the same title",
    )
    args = ap.parse_args()

    folder = Path(args.folder).resolve() if args.folder else prompt_swarm_folder()
    print(f"\nSwarm run: {folder}")

    issues = parse_swarm_run(folder)
    if not issues:
        print("No structured issues found in the swarm run output.", file=sys.stderr)
        sys.exit(1)

    print_preview(issues)

    if args.dry_run:
        print("--dry-run: stopping before any GitHub API calls.")
        return

    repo = args.repo or prompt_repo(detect_local_github_projects())
    print(f"\nTarget repo: {repo}")

    client = GitHubClient(repo=repo)
    client.authenticate()
    print("Authenticated.")

    existing_labels = client.list_labels()
    needed = sorted({lbl for it in issues for lbl in it.labels})
    for lbl in needed:
        client.ensure_label(lbl, existing_labels)

    created = 0
    skipped_existing = 0
    skipped_dup_in_batch = 0
    err_count = 0

    seen_titles: set[str] = set()
    for it in issues:
        # In-batch duplicate guard (same title twice in one run)
        if it.title in seen_titles:
            skipped_dup_in_batch += 1
            continue
        seen_titles.add(it.title)

        if not args.no_dedup:
            existing_num = client.find_open_issue_number(it)
            if existing_num is not None:
                print(f"  = already open #{existing_num} (skip): {it.title[:56]}")
                skipped_existing += 1
                continue

        try:
            num = client.create_issue(it.title, it.body, it.labels)
            print(f"  + created #{num}: {it.title[:56]}")
            created += 1
        except RuntimeError as e:
            print(f"  ! ERROR {it.title[:56]}: {e}", file=sys.stderr)
            err_count += 1
        # tiny backoff to respect rate limits
        if not args.yes and created % 20 == 0 and created:
            import time

            time.sleep(0.5)

    print(
        f"\nDone. created={created} skipped_existing={skipped_existing} "
        f"duplicate_in_batch={skipped_dup_in_batch} errors={err_count}"
    )
    if err_count:
        sys.exit(1)


if __name__ == "__main__":
    main()
